config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room, counter_cache: true
  # ActionCable
  broadcasts_to :room
  after_create_commit do
    broadcast_update_to "room-list", target: room, partial: "rooms/room", locals: {room: room}
    broadcast_update_to room, target: room, partial: "rooms/room_detail", locals: {room: room}
  end

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy

  # ActionCable
  after_create_commit do
    broadcast_prepend_to "room-list", target: "rooms", partial: "rooms/room"
  end
  after_update_commit do
    broadcast_replace_to "room-list", target: self, partial: "rooms/room"
    broadcast_update_to self, target: self, partial: "rooms/room_detail", locals: {room: self}
  end
  after_destroy_commit do
    broadcast_remove_to "room-list", target: self
    broadcast_replace_to self, target: "room-detail", partial: "shared/not_found"
  end

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_url, alert: "Not found."
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[new create]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all.order(created_at: :desc)
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireChatSandbox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p id="<%= dom_id message %>" style="margin-bottom: 0;">
  <%= message.content %>
</p>
<p style="color: gray; font-size: 0.8rem; text-align: right;">
  <%= time_ago_in_words(message.created_at) %>
</p>

app/views/messages/new.html.erb
<%= turbo_frame_tag "new_message", target: "_top" do %>
  <%= form_with(model: [@message.room, @message], data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |form| %>
    <div>
      <%= form.text_field :content, autocomplete: "off", class: "display: block; font-size: 1rem; line-height: 1.5; padding: 5px 10px;" %>
      <%= form.submit "Send", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, autocomplete: "off" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <div style="display: flex; align-items: center; flex-wrap: wrap; gap: 10px;">
    <p>
      <%= link_to room.name, room %>
    </p>
    <p style="color: gray;">
      <%= "(#{room.messages_count} messages)" %>
    </p>
  </div>
</div>

app/views/rooms/_room_detail.html.erb
<div id="<%= dom_id room %>">
  <div style="display: flex; align-items: center; flex-wrap: wrap; gap: 10px;">
    <h2>
      <%= room.name %>
    </h2>
    <p style="color: gray;">
      <%= "(#{room.messages_count} messages)" %>
    </p>
  </div>
  <div style="color: gray">
    <%= simple_format room.description %>
  </div>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render "form", room: @room %>
  <%= link_to "Cancel", @room %>
<% end %>

app/views/rooms/index.html.erb
<%= turbo_stream_from "room-list" %>

<div style="display: flex; align-items: center; justify-content: space-between;">
  <h1>Rooms</h1>
  <%= link_to "New room", new_room_path, class: "btn btn-primary" %>
</div>

<div id="rooms">
  <%= render @rooms %>
</div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<div id="room-detail">
  <%= turbo_frame_tag "room" do %>
    <div style="display: flex; flex-wrap: wrap; gap: 10px;">
      <%= link_to "Back to rooms", rooms_path, class: "btn btn-primary-outline", data: { turbo_frame: "_top" } %>
      <%= link_to "Edit this room", edit_room_path(@room), class: "btn btn-primary" %>
      <%= button_to "Destroy this room", @room, method: :delete, class: "btn btn-danger", form: { data: { turbo_confirm: "Are you sure?", turbo_frame: "_top" }} %>
    </div>
    <%= render partial: "rooms/room_detail", locals: { room: @room } %>
  <% end %>

  <h3>Messages</h3>

  <div id="messages">
    <%= render @room.messages %>
  </div>

  <%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>
</div>

app/views/shared/_not_found.html.erb
<p style="color: red;">This room already deleted.</p>
<p style="color: red;">Please back to <%= link_to "Home", root_path %>.</p>